FROM httpd:latest

RUN apt-get update; \
    apt-get install -y libjson-webtoken-perl; \
    rm -rf /var/lib/apt/lists/*

COPY ./my-printenv /usr/local/apache2/cgi-bin/printenv
COPY ./my-create-jwt /usr/local/apache2/cgi-bin/create-jwt
COPY ./my-redirect-template.html /usr/local/apache2/cgi-bin/redirect-template.html
COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./my-htpasswd /usr/local/apache2/htdocs/htpasswd

RUN chmod 755 /usr/local/apache2/cgi-bin/printenv \
              /usr/local/apache2/cgi-bin/create-jwt
