FROM httpd:latest
COPY ./public-html/ /usr/local/apache2/htdocs/
COPY ./my-printenv /usr/local/apache2/cgi-bin/printenv
COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf
RUN chmod 755 /usr/local/apache2/cgi-bin/printenv
