#!/usr/bin/perl

use strict;
use JSON;
use JSON::WebToken;

my $requestScheme=$ENV{'REQUEST_SCHEME'} || "http";
my $serverName=$ENV{'SERVER_NAME'} || "localhost";
my $remoteUser=$ENV{'REMOTE_USER'} or die "No user specified!";

my $query=$ENV{'QUERY_STRING'};
my $roomName = "ThisIsAVeryLongFallbackRoomNameAsSomethingWentWrong";
$roomName = $1 if $query =~ /^roomname=(.*)/;

my $displayName = "";
foreach my $part (split(/[ _]+/, $remoteUser)) {
  $part = $part."." if length($part) == 1;
  $displayName.=ucfirst($part)." ";
}
chop($displayName);

my $claims = {
    "aud" => "jitsi",
    "iss" => "my_jitsi_app_id",
    "room" =>  "$roomName",
    "context" => {
      "user" => {
        "name" => "$displayName",
        "email" => 'jitsi-user@example.com',
        "id" => "abcd:a1b2c3-d4e5f6-0abc1-23de-abcdef01fedcba"
      },
      "group" => "a123-123-456-789"
    }
};
my $secret = 'my_jitsi_app_secret';
 
my $jwt = encode_jwt($claims, $secret, "HS256", { "typ" => "JWT"});

print("Location: $requestScheme://$serverName/$roomName?jwt=$jwt\n\n");
